import type { ExportConfig } from "./types";
import tokensJson from "../../../../templates/assets/tokens/tokens.json";

export function generateDesignMdTemplate(config: ExportConfig): string {
  const { appName } = config;
  return [
    `# ${appName} — DESIGN.md`,
    "",
    "> 이 파일은 Studio Export 에서 생성된 템플릿입니다. 각 섹션을 실제 디자인 정보로 채워주세요.",
    "",
    "## 1. Visual Theme & Atmosphere",
    "",
    "> TODO — 브랜드의 전체적인 시각적 인상과 디자인 철학을 기술하세요.",
    "",
    "**Key Characteristics**:",
    "- (특성 1)",
    "- (특성 2)",
    "",
    "## 2. Color Palette & Roles",
    "",
    "> TODO — 색상 값과 시맨틱 역할을 정의하세요.",
    "",
    "- **Primary** (`#000000`): `--primary`. 핵심 브랜드 색상.",
    "",
    "## 3. Typography Rules",
    "",
    "> TODO — 폰트 패밀리, 타입 스케일, 웨이트를 정의하세요.",
    "",
    "**Font Family (Primary)**: `'Inter', system-ui, sans-serif`",
    "",
    "| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |",
    "|------|------|------|--------|-------------|----------------|-------|",
    "| Display | Inter | 56px | 300 | 1.03 | -1.4px | 히어로 |",
    "| Body | Inter | 16px | 400 | 1.6 | 0 | 기본 텍스트 |",
    "",
    "## 4. Component Stylings",
    "",
    "> TODO — 버튼, 카드 등 주요 컴포넌트의 시각 스타일을 기술하세요.",
    "",
    "## 5. Layout Principles",
    "",
    "**Spacing Base**: `4px`",
    "**Grid Max Width**: `1280px`",
    "",
    "> TODO — 그리드, 컨테이너, 여백 철학을 기술하세요.",
    "",
    "## 6. Depth & Elevation",
    "",
    "| Level | Treatment | Use |",
    "|-------|-----------|-----|",
    "| Level 0 | No shadow | 배경 |",
    "| Level 1 | `0 1px 3px rgba(0,0,0,0.1)` | 카드 |",
    "",
    "## 7. Do's and Don'ts",
    "",
    "### Do",
    "- 일관된 간격 시스템 사용",
    "",
    "### Don't",
    "- 폰트 패밀리 혼용",
    "",
    "## 8. Responsive Behavior",
    "",
    "> TODO — 브레이크포인트, 터치 타겟, 컬랩싱 전략을 기술하세요.",
    "",
    "## 9. Agent Prompt Guide",
    "",
    "> TODO — AI 에이전트 참조 가이드를 작성하세요.",
    "",
  ].join("\n");
}

export function generateRequirementsMdTemplate(config: ExportConfig): string {
  const { appName, appType, techStack } = config;
  return [
    `# ${appName} — REQUIREMENTS.md`,
    "",
    "> 이 파일은 Studio Export 에서 생성된 템플릿입니다.",
    "",
    "## 메타",
    "",
    "| 항목 | 값 |",
    "|---|---|",
    `| **앱 이름** | ${appName} |`,
    `| **앱 유형** | ${appType} |`,
    `| **기술 스택** | ${techStack} |`,
    "",
    "## NFR (Non-Functional Requirements)",
    "",
    "| 카테고리 | 항목 | 값 |",
    "|---|---|---|",
    "| 인증 | 방식 | email+password |",
    "| 다국어 | 지원 언어 | ko, en |",
    "| 테마 | 다크 모드 | 지원 |",
    "| 성능 | Lighthouse | 90+ |",
    "| 보안 | CSP | 활성화 |",
    "| 호환성 | 브라우저 | Chrome, Safari, Firefox |",
    "",
    "## 페이지 구성",
    "",
    "> TODO — 앱의 페이지 목록과 각 페이지 구성을 작성하세요.",
    "",
    "| 페이지 | Route | Variant | 설명 |",
    "|---|---|---|---|",
    "| (페이지명) | /route | page | 설명 |",
    "",
    "## 다음 단계",
    "",
    "1. DESIGN.md 시각 설계 완성",
    "2. AGENT.md 아키텍처 규칙 확정",
    "3. Paper 시안 작성",
    "4. React 구현",
    "",
  ].join("\n");
}

export function generateAgentMd(config: ExportConfig): string {
  const { appName, appType, techStack, packageManager } = config;
  return [
    `# ${appName} — AI Agent Guide`,
    "",
    "> AI 에이전트가 본 앱에서 코드를 생성할 때 따라야 할 지침.",
    "> `DESIGN.md` (시각) + `REQUIREMENTS.md` (기능) 와 함께 3종 세트로 사용.",
    "",
    "---",
    "",
    "## 1. 프로젝트 개요",
    "",
    "| 항목 | 값 |",
    "|---|---|",
    `| **앱 이름** | ${appName} |`,
    `| **패키지명** | \`${appName.toLowerCase().replace(/\s+/g, "-")}\` |`,
    `| **앱 유형** | ${appType} |`,
    `| **기술 스택** | ${techStack} |`,
    `| **패키지 매니저** | ${packageManager} |`,
    "",
    "## 2. 아키텍처 규칙",
    "",
    "### 컴포넌트 계층 (3-Layer)",
    "",
    "```",
    "templates/          Layer 3: Page Template (페이지 단위)",
    "    ↓ uses",
    "composites/         Layer 2: Composite (기능 단위)",
    "    ↓ uses",
    "ui/                 Layer 1: Primitive (shadcn/ui)",
    "```",
    "",
    "- **계층 의존 방향**: templates → composites → ui (역방향 금지)",
    "- **Primitive 수정 금지**: `ui/` 컴포넌트는 shadcn/ui CLI 로만 관리",
    "- **슬롯 필수**: 모든 Page Template 은 `texts`, `variant` prop 을 반드시 받는다",
    "",
    "## 3. 디렉토리 구조",
    "",
    "```",
    `src/`,
    `├── components/`,
    `│   ├── ui/          # Layer 1: Primitive`,
    `│   ├── composites/  # Layer 2: Composite`,
    `│   └── templates/   # Layer 3: Page Template`,
    `├── app/             # Router + 부트`,
    `└── i18n/            # 번역 리소스`,
    "```",
    "",
    "## 4. 코딩 규칙",
    "",
    "- TypeScript strict 모드 사용",
    "- 컴포넌트는 named export 만 사용 (default export 금지)",
    "- 스타일은 Tailwind utility class 만 사용 (inline style 금지)",
    `- 패키지 설치: \`${packageManager} add <package>\``,
    "",
  ].join("\n");
}

export function generateTokensJson(): string {
  return JSON.stringify(tokensJson, null, 2);
}
