/**
 * DESIGN.md 자동 렌더러 — Stitch DESIGN.md 0.1 superset.
 *
 * Stitch 9 섹션 (Overview / Colors / Typography / Layout / Elevation / Shapes /
 * Components / Do's-Don'ts / Iconography) 모두 보존 + 본 프로젝트 확장:
 * - §10 i18n schema
 * - §11 컴포넌트 인스턴스 어휘 (FRONT.md 참조)
 * - §12 Paper 매핑 컨벤션
 *
 * ADR-004 D-1 (Stitch superset 명칭 유지 — 사용자 결정 2026-05-10).
 * stitch-export.ts 가 Stitch subset 만 추출.
 */

import type { VocabularyCatalog } from "../catalog";

const AUTO_GENERATED_HEADER = `<!-- AUTO-GENERATED by studio/src/lib/vocabulary. DO NOT EDIT MANUALLY.
     Source: tokens.json (DTCG) + components/{ui,composites,templates}/*.tsx (cva).
     Format: Stitch DESIGN.md 0.1 superset. Stitch subset export via studio CLI. -->`;

interface DtcgLeaf {
  $value: unknown;
  $type?: string;
  $description?: string;
}

function isLeaf(node: unknown): node is DtcgLeaf {
  return typeof node === "object" && node !== null && "$value" in node;
}

function get(obj: Record<string, unknown>, path: string[]): unknown {
  let cursor: unknown = obj;
  for (const seg of path) {
    if (cursor && typeof cursor === "object" && seg in (cursor as Record<string, unknown>)) {
      cursor = (cursor as Record<string, unknown>)[seg];
    } else {
      return undefined;
    }
  }
  return cursor;
}

export interface RenderDesignMdOptions {
  catalog: VocabularyCatalog;
  tokens: Record<string, unknown>;
  /** 프로젝트 메타 (이름, 설명). */
  project?: {
    name?: string;
    description?: string;
    version?: string;
  };
}

export function renderDesignMd(options: RenderDesignMdOptions): string {
  const { catalog, tokens, project = {} } = options;
  const lines: string[] = [
    AUTO_GENERATED_HEADER,
    "",
    "---",
    "schema: design-md/0.1",
    "supersetOf: stitch-design-md/0.1",
    `name: ${project.name ?? "Design Project"}`,
    `version: ${project.version ?? "0.0.0"}`,
    "---",
    "",
    `# DESIGN.md — ${project.name ?? "Design Project"}`,
    "",
  ];

  // §1 Overview
  lines.push("## 1. Overview", "");
  lines.push(
    project.description ??
      "디자이너가 spec markdown 으로 작성, Paper 시각화, React (shadcn + Tailwind) 컴파일되는 4 축 어휘 정합 시스템.",
  );
  lines.push("");
  lines.push("**4-tier vocabulary**:");
  lines.push(`- ARIA roles: ${catalog.tiers.tier1Aria.roles.length}`);
  lines.push(`- shadcn primitives: ${catalog.tiers.tier2Shadcn.components.length}`);
  lines.push(`- composites: ${catalog.tiers.tier3Project.composites.length}`);
  lines.push(`- templates: ${catalog.tiers.tier3Project.templates.length}`);
  lines.push("");

  // §2 Colors
  lines.push("## 2. Colors", "");
  lines.push("Light scheme (DTCG references resolve via paper-sync):");
  lines.push("");
  lines.push("| Token | Value | Reference |");
  lines.push("|---|---|---|");
  const lightColor = get(tokens, ["semantic", "color", "light"]);
  if (lightColor && typeof lightColor === "object") {
    for (const [k, v] of Object.entries(lightColor)) {
      if (isLeaf(v)) {
        lines.push(`| \`--${k}\` | \`${String(v.$value)}\` | semantic.color.light.${k} |`);
      }
    }
  }
  lines.push("");

  // §3 Typography
  lines.push("## 3. Typography", "");
  const font = get(tokens, ["semantic", "font"]);
  if (font && typeof font === "object") {
    lines.push("| Family | Stack |");
    lines.push("|---|---|");
    for (const [k, v] of Object.entries(font)) {
      if (isLeaf(v)) {
        lines.push(`| \`${k}\` | \`${String(v.$value).replace(/\|/g, "\\|")}\` |`);
      }
    }
    lines.push("");
  }

  // §4 Layout
  lines.push("## 4. Layout", "");
  const size = get(tokens, ["semantic", "size"]);
  if (size && typeof size === "object") {
    lines.push("| Token | Value |");
    lines.push("|---|---|");
    for (const [k, v] of Object.entries(size)) {
      if (isLeaf(v)) {
        lines.push(`| \`${k}\` | \`${String(v.$value)}\` |`);
      }
    }
    lines.push("");
  }

  // §5 Elevation (현 프로젝트는 elevation 토큰 없음 — 컨벤션 명시)
  lines.push("## 5. Elevation", "");
  lines.push("Elevation tokens 미정의. shadcn `shadow-*` Tailwind class 컨벤션 사용.");
  lines.push("phase-7 후반 또는 phase-8 에서 elevation 토큰 추가 검토.");
  lines.push("");

  // §6 Shapes (radius)
  lines.push("## 6. Shapes", "");
  const radius = get(tokens, ["semantic", "radius"]);
  if (radius && typeof radius === "object") {
    lines.push("| Token | Value |");
    lines.push("|---|---|");
    for (const [k, v] of Object.entries(radius)) {
      if (isLeaf(v)) {
        lines.push(`| \`radius.${k}\` | \`${String(v.$value)}\` |`);
      }
    }
    lines.push("");
  }

  // §7 Components
  lines.push("## 7. Components", "");
  lines.push("3-tier 어휘 카탈로그. 상세는 `FRONT.md` 참조.");
  lines.push("");
  lines.push(`### Tier 2 — shadcn/ui (${catalog.tiers.tier2Shadcn.components.length})`);
  lines.push("");
  lines.push(
    catalog.tiers.tier2Shadcn.components.map((c) => `\`${c.name}\``).join(" · "),
  );
  lines.push("");
  lines.push(`### Tier 3 — composites (${catalog.tiers.tier3Project.composites.length})`);
  lines.push("");
  lines.push(
    catalog.tiers.tier3Project.composites.map((c) => `\`${c.name}\``).join(" · "),
  );
  lines.push("");
  lines.push(`### Tier 3 — templates (${catalog.tiers.tier3Project.templates.length})`);
  lines.push("");
  lines.push(
    catalog.tiers.tier3Project.templates.map((c) => `\`${c.name}\``).join(" · "),
  );
  lines.push("");

  // §8 Do's and Don'ts
  lines.push("## 8. Do's and Don'ts", "");
  lines.push("**Do**:");
  lines.push("- spec.md 에서 컴포넌트는 등록된 어휘만 사용");
  lines.push("- 색은 `var(--xxx)` 또는 `{{token.xxx}}` 참조만");
  lines.push("- variant 추가는 카탈로그 등재 절차 (Studio 마법사)");
  lines.push("- theme 단위 색 전환은 `<Section theme=\"brand-b\">` 컨벤션");
  lines.push("");
  lines.push("**Don't**:");
  lines.push("- raw 색상 값 (#hex / rgb / hsl / oklch) 직접 사용 금지");
  lines.push("- Tailwind class (`bg-red-500` 등) 직접 사용 금지 — 어휘 우회");
  lines.push("- 미등록 컴포넌트 사용 금지");
  lines.push("- theme nested override 금지 (단일 level)");
  lines.push("");

  // §9 Iconography
  lines.push("## 9. Iconography", "");
  lines.push("Lucide-react 기반 inline SVG. 시각 정합은 lucide path 정확 매핑 (phase-7 후반 ICONS 카탈로그).");
  lines.push("");

  // §10 (extension) i18n schema
  lines.push("## 10. i18n Schema (extension)", "");
  lines.push(
    "`{{i18n.<locale>.<key>}}` placeholder 가 spec.md 의 1 급 시민. 컴파일 시 `t()` 호출로 변환.",
  );
  lines.push("");
  lines.push("Asset 위치: `assets/i18n/<locale>.json`. 지원 locale: ko, en (확장 가능).");
  lines.push("");

  // §11 (extension) 컴포넌트 인스턴스 어휘
  lines.push("## 11. Component Instance Vocabulary (extension)", "");
  lines.push("ADR-004 D-3 의 4 layer 어휘. 상세는 `FRONT.md` 참조.");
  lines.push("");

  // §12 (extension) Paper 매핑 컨벤션
  lines.push("## 12. Paper Mapping Convention (extension)", "");
  lines.push("Paper 노드명 = `<ComponentName>[axis=value,...]`. 1:1 매핑.");
  lines.push("");

  return lines.join("\n");
}
