/**
 * FRONT.md 자동 렌더러 — 3-tier 어휘 카탈로그 → 프론트엔드 계약 문서.
 *
 * Studio export ZIP 의 FRONT.md (수동 편집 금지). spec.md 작성자(디자이너) +
 * AI codegen + Paper compiler 모두 본 문서를 어휘 reference 로 참조.
 *
 * ADR-004 D-3, D-5 의 3-tier 어휘 + Paper 컨벤션 명시.
 */

import type { VocabularyCatalog } from "../catalog";
import type { ExtractedComponent } from "../extractor";

const AUTO_GENERATED_HEADER = `<!-- AUTO-GENERATED by studio/src/lib/vocabulary. DO NOT EDIT MANUALLY.
     Source of truth: studio/src/components/{ui,composites,templates}/*.tsx (cva AST). -->`;

export function renderFrontMd(catalog: VocabularyCatalog): string {
  const { tier1Aria, tier2Shadcn, tier3Project } = catalog.tiers;
  const lines: string[] = [
    AUTO_GENERATED_HEADER,
    "",
    "# FRONT.md",
    "",
    "> 4 축 어휘 정합 카탈로그 — spec.md 작성 / Paper 시각화 / React 출력 / LLM 어휘 의 통합 ground.",
    "> 본 프로젝트의 *진짜 차별화 portion*: 4 축이 같은 어휘를 사용한다.",
    "",
    "## 어휘 layer (ADR-004 D-3)",
    "",
    "| Layer | 의미 | 예시 |",
    "|---|---|---|",
    "| L1 | 명명된 단일 variant | `<Button variant=\"primary\">` |",
    "| L2 | 다축 sub-variant | `<Button variant=\"primary\" size=\"lg\" tone=\"muted\">` |",
    "| L3 | theme context | `<Section theme=\"brand-b\">` |",
    "| L4 | 인라인 토큰 override | `tokens={{ \"--primary\": \"{{token.semantic.brand-2}}\" }}` |",
    "",
    "**raw 색상 금지**: hex / rgb / hsl / oklch 직접 사용 → spec.md lint ERROR.",
    "**미등록 어휘 금지**: 카탈로그에 없는 컴포넌트 / variant / theme → ERROR.",
    "",
    `## Tier 1 — ARIA roles (${tier1Aria.roles.length})`,
    "",
    "*최저층 의미 — accessibility 자동 정합. shadcn 컴포넌트의 ariaRole 매핑 reference.*",
    "",
    `Spec: ${tier1Aria.specMeta.version} ([source](${tier1Aria.specMeta.source}))`,
    "",
    `<details><summary>전체 ${tier1Aria.roles.length} role 보기</summary>`,
    "",
  ];

  // ARIA roles by category
  const byCat = new Map<string, typeof tier1Aria.roles>();
  for (const r of tier1Aria.roles) {
    if (!byCat.has(r.category)) byCat.set(r.category, []);
    byCat.get(r.category)!.push(r);
  }
  for (const [cat, list] of byCat) {
    lines.push(`### ${cat} (${list.length})`, "");
    lines.push(list.map((r) => `\`${r.name}\``).join(" · "));
    lines.push("");
  }
  lines.push("</details>", "");

  // Tier 2 — shadcn
  lines.push(
    `## Tier 2 — shadcn/ui primitives (${tier2Shadcn.components.length})`,
    "",
    `*${tier2Shadcn.directory} 의 cva-based 컴포넌트. LLM 훈련 데이터 풍부 = 환각 ↓.*`,
    "",
  );
  for (const c of tier2Shadcn.components) {
    lines.push(...renderComponent(c));
  }

  // Tier 3 — project composites
  lines.push(
    `## Tier 3 — Project composites (${tier3Project.composites.length})`,
    "",
    "*shadcn primitives 의 도메인-specific 조합. spec.md 의 상위 어휘.*",
    "",
  );
  for (const c of tier3Project.composites) {
    lines.push(...renderComponent(c));
  }

  // Tier 3 — templates
  lines.push(
    `## Tier 3 — Project templates (${tier3Project.templates.length})`,
    "",
    "*페이지 매크로 어휘. variant 로 layout (page/modal/bottom-sheet) 전환.*",
    "",
  );
  for (const c of tier3Project.templates) {
    lines.push(...renderComponent(c));
  }

  // Paper 컨벤션
  lines.push(
    "## Paper 노드명 컨벤션",
    "",
    "Paper 노드명이 React 컴포넌트와 1:1 매핑되는 grammar:",
    "",
    "```",
    "<ComponentName>[variant=value,size=value,...]",
    "```",
    "",
    "예시:",
    "- `Button[variant=destructive,size=sm]` ⟷ `<Button variant=\"destructive\" size=\"sm\">`",
    "- `LoginPage[variant=page,brand=a]` ⟷ `<LoginPage variant=\"page\" brand=\"a\">`",
    "- 미등록 노드 = raw 영역 (1:1 보장 X, 추론 영역)",
    "",
  );

  // shadcn registry 안내
  lines.push(
    "## shadcn registry 출력",
    "",
    "본 카탈로그의 Tier 2/3 컴포넌트는 *shadcn registry-item.json 형식* 으로 출력 가능.",
    "외부 codebase 에서 install:",
    "",
    "```bash",
    "npx shadcn@latest add @designmd/<component-name>",
    "```",
    "",
    "ADR-004 D-6 — 컴파일러 출력 = registry-item.json 형식.",
    "",
  );

  return lines.join("\n");
}

function renderComponent(c: ExtractedComponent): string[] {
  const lines: string[] = [];
  lines.push(`### ${c.name}`, "");
  lines.push(`- **File**: \`${c.filePath}\``);
  lines.push(`- **Pattern**: ${c.pattern}`);
  if (c.ariaRole) lines.push(`- **ARIA role**: \`${c.ariaRole}\``);
  if (c.axes.length === 0) {
    lines.push(`- **Axes**: (no cva variants — composite/template)`);
  } else {
    lines.push(`- **Axes**:`);
    for (const ax of c.axes) {
      const def = c.defaultVariants[ax.name];
      const valueStr = ax.values.map((v) => (v === def ? `**${v}**` : v)).join(" · ");
      lines.push(`  - \`${ax.name}\`: ${valueStr}${def ? ` *(default: ${def})*` : ""}`);
    }
  }
  lines.push("");
  return lines;
}
