/**
 * TOKEN.md 자동 렌더러 — DTCG 1.0 tokens → human-readable markdown.
 *
 * 출력은 Studio export ZIP 의 TOKEN.md (수동 편집 금지 마커 포함).
 * ADR-004 D-2 (DTCG 호환) — TOKEN.md 가 외부 도구와 *공통 형식* 의 사람 친화 view.
 */

const AUTO_GENERATED_HEADER = `<!-- AUTO-GENERATED by studio/src/lib/vocabulary. DO NOT EDIT MANUALLY.
     Source of truth: templates/assets/tokens/tokens.json (DTCG 1.0). -->`;

interface DtcgLeaf {
  $value: unknown;
  $type?: string;
  $description?: string;
}

type DtcgNode = DtcgLeaf | { [key: string]: unknown };

function isLeaf(node: unknown): node is DtcgLeaf {
  return typeof node === "object" && node !== null && "$value" in node;
}

interface FlatToken {
  path: string;
  value: string;
  type: string;
  description?: string;
}

function flatten(
  node: Record<string, unknown>,
  pathSegments: string[],
  inheritedType: string | undefined,
  out: FlatToken[],
): void {
  const explicitType = (node as { $type?: string }).$type;
  const groupType = explicitType ?? inheritedType;
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const childPath = [...pathSegments, key];
    if (isLeaf(value)) {
      const leaf = value as DtcgLeaf;
      out.push({
        path: childPath.join("."),
        value: String(leaf.$value),
        type: leaf.$type ?? groupType ?? "(unspecified)",
        description: leaf.$description,
      });
    } else if (typeof value === "object" && value !== null) {
      flatten(value as Record<string, unknown>, childPath, groupType, out);
    }
  }
}

export interface RenderTokenMdOptions {
  tokens: Record<string, unknown>;
  /** 헤더에 표시할 spec 메타. */
  specVersion?: string;
}

export function renderTokenMd(options: RenderTokenMdOptions): string {
  const { tokens, specVersion = "DTCG 1.0 (W3C 2025-10 stable)" } = options;
  const flat: FlatToken[] = [];
  flatten(tokens, [], undefined, flat);

  // Group by top-level (primitive / semantic / ...).
  const grouped = new Map<string, FlatToken[]>();
  for (const t of flat) {
    const top = t.path.split(".")[0];
    if (!grouped.has(top)) grouped.set(top, []);
    grouped.get(top)!.push(t);
  }

  const lines: string[] = [
    AUTO_GENERATED_HEADER,
    "",
    "# TOKEN.md",
    "",
    `> Design tokens — ${specVersion}.`,
    "> 외부 도구 (Style Dictionary v4+, Tokens Studio, Stitch DESIGN.md) 와 호환.",
    "",
    `**Total tokens**: ${flat.length}`,
    "",
  ];

  for (const [top, items] of grouped) {
    lines.push(`## ${capitalize(top)}`, "");
    lines.push("| Path | Value | Type | Description |");
    lines.push("|---|---|---|---|");
    for (const t of items) {
      lines.push(
        `| \`${t.path}\` | \`${escapePipes(t.value)}\` | ${t.type} | ${t.description ?? ""} |`,
      );
    }
    lines.push("");
  }

  lines.push("## 변환 명령", "");
  lines.push("```bash");
  lines.push("# DTCG → CSS variables (build-time)");
  lines.push("pnpm tokens          # studio/tokens/build.mjs");
  lines.push("# 외부 호환 export");
  lines.push("# - Style Dictionary v4+: 직접 사용 가능");
  lines.push("# - Tokens Studio: import 가능");
  lines.push("# - Stitch DESIGN.md: studio export 시 자동 변환");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s ? s[0].toUpperCase() + s.slice(1) : s;
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}
